const data = [12, "ani", true, false, 001, [2, 4, 5, 6, 7, 8]];
console.log(data[5][2]);
data[3] = 21;
console.log(data);
data.length;
console.log(data.length);
data.pop();
console.log(data);
data.push(20);
console.log(data);
data.shift(20);
console.log(data);
data.slice(2, 4);
console.log(data.slice(2, 4));
data.shift();
console.log(data);
data.unshift;
console.log(data);
